### ISSUE TITLE
Nobody up votes: is it design issue, may be the icon does not convey the clear meaning.

### ISSUE THREAD

**Issue by curran** [vizhub-core/vizhub-issue-tracker#402]

**Comment by stushurik** [comment]
yeah maybe better thumb up and down

**Comment by waseem-medhat** [comment]
![image](https://user-images.githubusercontent.com/41170102/102257450-6e295e00-3f15-11eb-912a-ae2dd26b5592.png)

This reactions section appears below LinkedIn posts. So, how about implementing something similar (in the viz/editor page, not the home) instead of only showing the number? If your assumption about the icon not conveying the meaning, having a section with the label "Upvotes" should be clearer.

I believe that the up arrow is not that vague. Maybe the idea of upvoting itself doesn't come naturally for someone getting started with a visualization platform... until they realize it exists!

**Comment by nitanagdeote** [comment]
"Reactions" looks like a good idea
